FROM alpine:latest

RUN apk add --no-cache nginx

RUN mkdir -p /usr/share/nginx/html

RUN echo "<h1>Application Deployed via Terraform IaC!</h1>" > /usr/share/nginx/html/index.html

# 🔥 IMPORTANT: replace broken default config
RUN printf "server {\n\
    listen 80 default_server;\n\
    listen [::]:80 default_server;\n\
\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
\n\
    location / {\n\
        try_files \$uri \$uri/ =404;\n\
    }\n\
}\n" > /etc/nginx/http.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]